DROP DATABASE realstate;
CREATE DATABASE realstate;
USE realstate;
DROP TABLE IF EXISTS users_addresses;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS countries;
DROP TABLE IF EXISTS cities;
DROP TABLE IF EXISTS streets;
DROP TABLE IF EXISTS streets_num;
DROP TABLE IF EXISTS staircases;
DROP TABLE IF EXISTS floors;
DROP TABLE IF EXISTS doors;
DROP TABLE IF EXISTS zipcodes;
DROP TABLE IF EXISTS addresses;
DROP TABLE IF EXISTS users_addresses;

CREATE TABLE countries (id_country INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT, country VARCHAR(64) NOT NULL);

CREATE TABLE cities (id_city INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT, city VARCHAR(64) NOT NULL, id_country INT UNSIGNED NOT NULL, FOREIGN KEY(id_country) REFERENCES countries(id_country));

CREATE TABLE streets (id_street BIGINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT, street VARCHAR(32) NOT NULL, id_city INT UNSIGNED NOT NULL, FOREIGN KEY(id_city) REFERENCES cities(id_city));

CREATE TABLE streets_num (id_street_num INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT, street_num VARCHAR(16));

CREATE TABLE staircases (id_staircase INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT, staircase VARCHAR(8));

CREATE TABLE floors (id_floor INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT, `floor` VARCHAR(8));

CREATE TABLE doors (id_door INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT, door VARCHAR(8));

CREATE TABLE zipcodes (id_zipcode INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT, zipcode VARCHAR(16) NOT NULL);

CREATE TABLE addresses (id_address BIGINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT, id_street INT UNSIGNED NOT NULL, id_street_num INT UNSIGNED NOT NULL, id_staircase INT UNSIGNED NOT NULL, id_floor INT UNSIGNED NOT NULL, id_door INT UNSIGNED NOT NULL, id_zipcode INT UNSIGNED NOT NULL, FOREIGN KEY(id_street) REFERENCES streets(id_street), FOREIGN KEY(id_street_num) REFERENCES streets_num(id_street_num), FOREIGN KEY(id_staircase) REFERENCES staircases(id_staircase), FOREIGN KEY(id_floor) REFERENCES floors(id_floor), FOREIGN KEY(id_door) REFERENCES doors(id_door), FOREIGN KEY(id_zipcode) REFERENCES zipcodes(id_zipcode));

CREATE TABLE users (id_user BIGINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT);

CREATE TABLE users_addresses (id_user_address BIGINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT, id_user BIGINT UNSIGNED NOT NULL, id_address BIGINT UNSIGNED NOT NULL, FOREIGN KEY(id_user) REFERENCES users(id_user), FOREIGN KEY (id_address) REFERENCES addresses(id_address)); 
